/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MenuSmartTv;

public class App {
  
    public static void main(String[] args) {
        SmartTv smartTv = new SmartTv(); //An instance of "SmartTv" to interact with its methods
        smartTv.turnOnTv();
        smartTv.initialize();
        
    }
}
